name: Check issue template

on:
  issues:
    types: [opened]

jobs:
  check-template:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue template
      id: check-template
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue;
          const templates = ["bug_report.md", "enhancement.md", "feature_request.md"];
          let templateMatched = false;

          async function checkTemplate(template) {
            const {data: templateContent} = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: `.github/ISSUE_TEMPLATE/${template}`
            });
            const content = Buffer.from(issue.body, 'base64').toString();
            if (content === templateContent.content) {
              console.log(`Issue template ${template} has not been changed.`);
              templateMatched = true;
            }
          }

          async function run() {
            const { GitHub, context } = require('@actions/github');
            const github = new GitHub(process.env.GITHUB_TOKEN);
            for (const template of templates) {
              await checkTemplate(template);
            }

            if (!templateMatched) {
              console.log('Issue template has been changed.');
            } else {
              const params = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              }
              await github.issues.update(params);
            }
          }

          run();
